baseurl = "http://zhengyhn.github.io/"
languageCode = "en-us"
title = "Hank's Blog"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "About"
  weight = 2
  identifier = "about"
  url = "/about/"


[params]
  Subtitle = "坚持做一件事，然后静静地等待时间的回报"

  GithubId = "zhengyhn"

  Summary = false # takes true or false
  Content = false  # takes true or false
